### PR TITLE
feat(markdown): update line-number

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Still, another improvement for "Read mode"

**Comment by Mister-Hope** [comment]
BTW, this css style is quite safe to use:

image

**Comment by meteorlxy** [comment]
> The previous one still not work well in some browsers.

Any repro/screenshots? Modifying the markdown plugin will affect all community themes who rely on it.

**Comment by Mister-Hope** [comment]
yep，but I think rare plugin would do something to line number or highlight
 part.l, since I am not editing the outer structure, so they should still be able to select the part they want.

At least my plugin would work fine.

I will provide a screenshot later as you request.

**Comment by Mister-Hope** [comment]
Before:

image

After:

image

**Comment by Mister-Hope** [comment]
Like I said, there is acually no difference.

**Comment by meteorlxy** [comment]
> Like I said, there is acually no difference.

I was asking for the differences / improvements 😅

**Pull request merged**
