### PR TITLE
docs: update emoji-cheat-sheet website

### PR DESCRIPTION
**Pull request by cabbage9**
emoji-cheat-sheet.com is something wrong, and I search it in google, fortunately, I found this new website https://www.webfx.com/tools/emoji-cheat-sheet/
If need to change text ([emoji-cheat-sheet.com]) in paragraph, just let me know your decision or change it again by yourself.

### CODE REVIEW

**Comment by meteorlxy** [comment]
Please also update the English docs

**Comment by cabbage9** [comment]
> Please also update the English docs

done

**Comment by meteorlxy** [comment]
I think it could be better to point to some open source project like https://github.com/ikatyang/emoji-cheat-sheet

**Comment by meteorlxy** [comment]
Just updated the link to the project I mentioned above.

Thanks for pointing out this anyway.

**Comment by cabbage9** [comment]
Sorry for reply so late, a little busy now, feel free to change the links and headings as you see fit, my pleasure.

**Pull request merged**
