### PR TITLE
feat: improvements and bug fixes about default theme

### PR DESCRIPTION
**Pull request by Mister-Hope**
@meteorlxy I can help rebuilding all the styles of default theme with css and css variables. Do you want me to proceed it?

### CODE REVIEW

**Comment by meteorlxy** [comment]
You'd better split it into separate PRs.

**Comment by meteorlxy** [comment]
We don't need to refactor the styles in a hurry. The layouts & theme system still have some changes to be determined.

**Comment by meteorlxy** [comment]
But it's OK to start doing that. I think we will finally use pure CSS in most official packages.

**Review by kadirselcuk — APPROVED** [review]

**Review by kadirselcuk — APPROVED** [review]

**Comment by meteorlxy** [comment]
@Mister-Hope Could you please split this PR into separate ones?

**Comment by meteorlxy** [comment]
Closing as the fix is valid, but the feature is invalid.

**Pull request closed without merging**
