### PR TITLE
fix(client): fix defineClientConfig will get undefined in HMR

### LINKED ISSUE #1154: [Bug report] HMR of vue components with usePageData() errros
### Description

1. Add registerComponentsPlugin
```ts
  plugins: [
    registerComponentsPlugin({
      componentsDir: path.resolve(__dirname, '../../components'),
    }),
  ],
```

2. Add a component **with** `usePageData()`
```vue
<template>
  <div>
    aa
    <pre>{{ pageData }}</pre>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { usePageData } from '@vuepress/client';

export default defineComponent({
  setup() {
    return {
      pageData: usePageData()
    };
  },
});
</script>
```

3. Put it in a md-page

4. Edit the component

```
client.ts:113 TypeError: defineClientConfig is not a function
    at config.js?t=1667648196081&v=987cdd9b:7:16
warnFailedFetch @ client:264
fetchUpdate @ client:506
await in fetchUpdate (async)
(anonymous) @ client:306
handleMessage @ client:304
(anonymous) @ client:246
dispatchEvent @ .localservice@runtime.a0ea75dd36396805bd36e49d0b54d86602583e15.js:1
_handleMessage @ .localservice@runtime.a0ea75dd36396805bd36e49d0b54d86602583e15.js:7
_0x2dff07 @ .localservice@runtime.a0ea75dd36396805bd36e49d0b54d86602583e15.js:7

client.ts:115 [hmr] Failed to reload /@fs/home/projects/vuepress-uy4riu/components/MyComp.vue. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

### Reproduction

https://stackblitz.com/edit/vuepress-uy4riu?file=docs%2F.vuepress%2Fconfig.ts,components%2FMyComp.vue,docs%2FREADME.md

### Used Package Manager

npm

### System Info

```shell
./node_modules/.bin/vuepress info

  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Utilities:
    Git: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.53 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.53 
    @vuepress/client:  2.0.0-beta.53 
    @vuepress/core:  2.0.0-beta.53 
    @vuepress/markdown:  2.0.0-beta.53 
    @vuepress/plugin-active-header-links:  2.0.0-beta.53 
    @vuepress/plugin-back-to-top:  2.0.0-beta.53 
    @vuepress/plugin-container:  2.0.0-beta.53 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.53 
    @vuepress/plugin-git:  2.0.0-beta.53 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.53 
    @vuepress/plugin-nprogress:  2.0.0-beta.53 
    @vuepress/plugin-palette:  2.0.0-beta.53 
    @vuepress/plugin-prismjs:  2.0.0-beta.53 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.53 => 2.0.0-beta.53 
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.53 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.53 
    @vuepress/theme-default:  2.0.0-beta.53 
    @vuepress/utils:  2.0.0-beta.53 
    vue:  3.2.41 
    vue-loader: Not Found
    vue-router:  4.1.6 
    vuepress: ^2.0.0-beta.53 => 2.0.0-beta.53 
    vuepress-vite:  2.0.0-beta.53 
    vuepress-webpack: Not Found
```

### PR DESCRIPTION
**Pull request by tinyfind**
fixed #1154

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Why shall your pr fix the issue, any explanation?

**Comment by tinyfind** [comment]
when the Component import thing in `'@vuepress/client'` and trigger HMR update
will exit rely error in deep loops , like this issue in vite https://github.com/vitejs/vite/issues/3033#issue-860500198

**Dev server:** `app-> chunk -> clientConfigs -> client -> chunk`
 in this import path, rely have no problem
**HMR update:** `component -> client -> chunk -> clientConfigs -> client`
in this import path, `clientConfigs `rely methods **defineClientConfig** from `client `,but that method is not yet init in this time, so make error.

**code_dev**
https://github.com/vuepress/vuepress-next/blob/8c345d827c758326429b20f37b6be95f0865c655/packages/client/src/helpers/defineClientConfig.ts#L6
**code_build**`\@vuepress\client\dist\index.js#31`
```js
// src/helpers/defineClientConfig.ts
var defineClientConfig = (clientConfig = {})=>clientConfig
```
>if use `var `, because hosting of var, so the method is undefined, #1154 
if use `function`, because first level, so the method will init earlier than import
if use `ler or const ` will cause `temporal dead zon`

**Comment by tinyfind** [comment]
> Uh, so this is definitely caused by circular deps in the build dist file.

yes, use function can avoid it

**Comment by meteorlxy** [comment]
> yes, use function can avoid it

Well, it's kind of a workaround. We still need to solve the circular deps issue.

**Comment by meteorlxy** [comment]
Fixed by https://github.com/vuepress/vuepress-next/commit/b0a7a0e686b98dd8201dfed8effd6f7616e7d498

Thanks for your contribution ❤️ .

**Comment by tinyfind** [comment]
> Fixed by [b0a7a0e](https://github.com/vuepress/vuepress-next/commit/b0a7a0e686b98dd8201dfed8effd6f7616e7d498)
> 
> Thanks for your contribution ❤️ .
you are welcome

**Pull request closed without merging**
