### PR TITLE
fix(client): fix double quote in head tag

### LINKED ISSUE #1174: [Bug report] doule quote in head tag content cause issues in devServer
### Description

```md
---
head:
  - - meta
    - name: test
      content: 'some text with "double quote"'

---

Content
```

image

The css selector is not valid anymore under this situation.

### PR DESCRIPTION
**Pull request by tinyfind**
fixed #1174 https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2448#issue-1461331094

### CODE REVIEW

**Comment by Mister-Hope** [comment]
You’d better explain why JSON.stringing is needed.

**Comment by Mister-Hope** [comment]
Closing as this is not a valid fix, if attr contain space, you fix can cause similar issue.

**Comment by tinyfind** [comment]
> Closing as this is not a valid fix, if attr contain space, you fix can cause similar issue.

sure?  can you give me an example

**Comment by tinyfind** [comment]
> You’d better explain why JSON.stringify is needed.

> `'some text with "double quote"'` valid string
https://github.com/vuepress/vuepress-next/blob/8c345d827c758326429b20f37b6be95f0865c655/packages/client/src/setupUpdateHead.ts#L88
but here will transform that to "`some text with "double quote""`，it's invalid
so use  `""` or `''`  will generate invalid string,

**Comment by Mister-Hope** [comment]
```html
<meta name="description" value="Some words here" />
```

**Review by Mister-Hope — APPROVED** [review]

**Pull request merged**
