### PR TITLE
feat(bundler-vite): improve chunk name

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
This ensure a chunk is not started by `_`, solution comming from vitepress, the idea is edit the original `sanitizeFileName` and remove the trailling underscore.

**Review by meteorlxy — CHANGES_REQUESTED** [review]
Fix the CI warning

**Comment by Mister-Hope** [comment]
Done

**Comment by Mister-Hope** [comment]
Edge case: people are using markdown starting with `_`, I will fix this and then mark this ready.

**Comment by Mister-Hope** [comment]
Any update on reviewing this?

**Comment by Mister-Hope** [comment]
Emm that function is redirectly copied from rollup, and was used exactly on the same option.

I though we can trust rollup code as we are using rollup ourselves. however if you do insist a unit test is still needed, I can add some.

**Comment by meteorlxy** [comment]
OK, I forgot that is was forked from rollup. Ignore that.

**Pull request merged**
