### PR TITLE
fix(theme-default): `scrollBehavior` will be executed after the transition ends

### LINKED ISSUE #77: [Bug report] navigate to anchor on another page does not work
### Description

Navigation to anchor on another page does not work. In dev mode, the browser will receive a warning message from vue-router. 

```
  Couldn't find element using selector "#plugins" returned by scrollBehavior.
```

### Steps to reproduce

- Reproduction link / repo: https://vuepress2.netlify.app/guide/plugin.html

### Expected behavior

Navigation to anchor 

### Screenshots

vuepress-next

### Environment info

- Browser: Chrome 89.0.4389.90

### PR DESCRIPTION
**Pull request by John60676**
Fixes #77

### CODE REVIEW

**Comment by meteorlxy** [comment]
Sorry I didn't notice your PR :sweat:.

This has been fixed in 4b8d0cff2d7fa3d74d69d551976a3b12263e6124.

Thank you all the same :heart: :+1:

**Comment by John60676** [comment]
@meteorlxy 

It doesn't matter, your solution is better 👍. There is another problem here. When the website is opened for the first time, the anchor will still fail to jump. Adding `useScrollPromise().pending()` in `defineClientAppEnhance` can solve this problem.

**Comment by meteorlxy** [comment]
@John60676 

I think the initial `scrollPromise.pending()` does not help, because the transition will not be triggered on initial load, and the Promise will be pending forever. 🤔 

It should not happen in build mode as all the anchors have already been pre-rendered.

**Comment by John60676** [comment]
> It should not happen in build mode as all the anchors have already been pre-rendered.

Yes, you are right, this will not happen in build mode.

**Pull request closed without merging**
