### PR TITLE
fix(theme-default): only show toggleSidebarButton when necessary, fix…

### PR DESCRIPTION
**Pull request by Mister-Hope**
… #696

### CODE REVIEW

**Comment by meteorlxy** [comment]
The toggle sidebar button is also used for navbar 🤔

**Comment by Mister-Hope** [comment]
🤣 Thanks reminding that because I moved navbar items to a new place in my theme.
image

**Comment by Mister-Hope** [comment]
Then it will need a refactor here, maybe I should make navbar items global provided like sidebaritems.

**Comment by Mister-Hope** [comment]
Closing it first.

I will try to make some refactors to improve this.

Just realized that gestures can invoke sidebar either.

Also, here is a werid logic:

- When users disable sidebar, they won't find the toggle sidebar button to show sidebar on mobile with a valid sidebar config.

**Pull request closed without merging**
