### PR TITLE
support async function exported in vuepress config

### PR DESCRIPTION
**Pull request by dz85**
### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/vuepress/vuepress-next/blob/main/docs/contributing.md).
- [x] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New feature
- [x] Documentation update
- [ ] Other

### Description

support both `function` form and `async function` form when using vuepress config file with both `vuepress dev` and `vuepress build`.

more about this:

- https://github.com/vuejs/vuepress/pull/1925
- https://github.com/vuejs/vuepress/issues/1185

### Screenshots

**Before**

**After**

### CODE REVIEW

**Comment by dz85** [comment]
more about this: https://github.com/vuejs/vuepress/pull/1925

**Comment by Mister-Hope** [comment]
Can't you write top level await directly? E.g.:

```js
const options = await getOptions()

export default options
```

So what does your pr actually solves?

**Review by Mister-Hope — COMMENTED** [review]
I don't see any necessity of this or, please explain.

**Comment by meteorlxy** [comment]
Closing per [this](https://github.com/vuepress/vuepress-next/pull/1376#issuecomment-1621096157)

**Pull request closed without merging**
