### PR TITLE
fix(theme-default): fix word breaking, close #1209

### LINKED ISSUE #1209: [Bug report] Long word in title will break layout
### Description

image

### Reproduction

Not needed

### Used Package Manager

pnpm

### System Info

```shell
Not related
```

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by meteorlxy** [comment]
@Mister-Hope 

- Please provide "before" and "after" screenshots for this kind of UI changes.
- Please add (close #xxx) in commit message or PR title if this PR is to solve some issue.

**Comment by Mister-Hope** [comment]
Before:

image

After:

image

**Comment by Mister-Hope** [comment]
Done

**Comment by Mister-Hope** [comment]
A resonable production content can be `configA.configB.configC.configD.configE`

image

**Review by meteorlxy — APPROVED** [review]

**Pull request merged**
