### PR TITLE
docs: format deployment & update actions-gh-pages

### PR DESCRIPTION
**Pull request by YunYouJun**
- format deployment.md with [markdownlint](https://github.com/DavidAnson/markdownlint)
  - Add indent for list
- use [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) instead of [ghaction-github-pages](https://github.com/crazy-max/ghaction-github-pages)
  - The former is more popular, and updates are active.
  - More detailed documentation.
  - Its name is more friendly, and it is deployed to gh-pages by default.

### CODE REVIEW

**Comment by meteorlxy** [comment]
Don't format like that. The indentation is avoided intentionally

**Comment by meteorlxy** [comment]
Closing as it's not necessary to replace a project which is working properly. And it's only an example, users can choose other projects themselves

**Comment by YunYouJun** [comment]
> Don't format like that. The indentation is avoided intentionally

I am not simply using markdownlint for automatic formatting.

I noticed that the indentation after the list is inconsistent, some are indented, and some are not.

image

After the changes are made, the uniformity of the style can be maintained, and no problems caused by this have been found so far.

image

**Comment by YunYouJun** [comment]
> Closing as it's not necessary to replace a project which is working properly. And it's only an example, users can choose other projects themselves

I think that when the functions of the projects are almost the same, it is necessary to use projects with more detailed documentation and more active maintenance as examples. Users can more easily find some potential solutions from the project.

Although the choice of items is free, users will follow the document examples more to use, and will not think of another good choice.

**Comment by YunYouJun** [comment]
Of course, these are my personal opinions. If I can't persuade you, just leave it here.

**Comment by Mister-Hope** [comment]
I agree with you maybe we can add a linter (some mistaken trailling white space or missing some white space is bothering me too), but the action is just personal taste.

E.g.: for me I am using https://github.com/JamesIves/github-pages-deploy-action

**Comment by YunYouJun** [comment]
> I agree with you maybe we can add a linter (some mistaken trailling white space or missing some white space is bothering me too), but the action is just personal taste. If it's working fine, and does work fine in most situations, then it's good to use.
> 
> E.g.: for me I am using https://github.com/JamesIves/github-pages-deploy-action

Yeah, I see, I can separate them if needed.

**Comment by meteorlxy** [comment]
If you take a look at the file history, you might find that we used to have those indents. However, it looks bad on mobile devices.

**Comment by YunYouJun** [comment]
I may understand what you mean.

Do you mean this?

image

image

Is it a better way to customize the code block style in `<li></li>` for the mobile?

**Comment by Mister-Hope** [comment]
I think we can use tools (whichi won't be much strict) like prettier to format markdown, I just tried, prettier won't force indent that list.

Just like [here](https://github.com/vuepress/vuepress-next/pull/275/commits/471ee26c60939c0bc305231415661fd54dd38f6c#diff-a80a5ac6d641cce4f0b8e2c4c785b7529eed8069c21f79de9466029bd53d3537) in line 61, these issues won't be nice.

**Pull request closed without merging**
