### PR TITLE
git commit -am "fix(code-scss): 修复代码块行号与代码对应不齐问题 (close #901)"

### LINKED ISSUE #901: Line number and code block lines misalign in some devices
### Description

目前版本：`2.0.0-beta.45`  

当代码块行数很多时，行号与代码对应不齐问题，如下图所示  
image

通过重写`div[class*=language-].line-numbers-mode .line-numbers .line-number`样式`height: 1.377em;`自行修复后如下所示  
image

### Reproduction

https://apidocs.cn/blog/front/css/%E5%A5%BD%E7%9C%8B%E7%9A%84%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BBCSS%E6%A0%B7%E5%BC%8F.html

### Used Package Manager

npm

### System Info

```shell
***@localhost my-blog % vuepress info

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 540.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 94.0.4606.71
    Edge: Not Found
    Firefox: 100.0.1
    Safari: 15.4
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45 
    @vuepress/client:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/core:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/markdown:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/plugin-active-header-links:  2.0.0-beta.45 
    @vuepress/plugin-back-to-top:  2.0.0-beta.45 
    @vuepress/plugin-container:  2.0.0-beta.45 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45 
    @vuepress/plugin-git:  2.0.0-beta.45 
    @vuepress/plugin-google-analytics: ^2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-medium-zoom:  2.0.0-beta.45 
    @vuepress/plugin-nprogress:  2.0.0-beta.45 
    @vuepress/plugin-palette:  2.0.0-beta.45 
    @vuepress/plugin-prismjs:  2.0.0-beta.45 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-search: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-shiki: ^2.0.0-beta.5 => 2.0.0-beta.5 
    @vuepress/plugin-theme-data:  2.0.0-beta.45 
    @vuepress/plugin-toc: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/shared:  2.0.0-beta.45 (2.0.0-beta.4)
    @vuepress/theme-default:  2.0.0-beta.45 
    @vuepress/utils:  2.0.0-beta.45 (2.0.0-beta.5)
    vue:  3.2.33 
    vue-loader: Not Found
    vue-router:  4.0.15 
    vuepress: 2.0.0-beta.45 => 2.0.0-beta.45 
    vuepress-vite:  undefined (2.0.0-beta.45)
    vuepress-webpack: Not Found
```

### PR DESCRIPTION
**Pull request by dingqianwen**
通过测试

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Any reason why it's 1.377 instead of 1.4? This is required before merging.

**Comment by dingqianwen** [comment]
> 

因为一点点尝试与测试，发现这个数是最标准的，无论代码块行数是多少都适应。

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/issues/901#issuecomment-1133742129

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
Reason  required before merging

**Comment by Mister-Hope** [comment]
If you try vuepress-theme-hope, you can find that the code line is aligning, but I can tell you that I am using `line-height: 1.4` as well,

image

The reason matters as we should try to make things clear.

**Pull request closed without merging**
