### PR TITLE
fix(theme-default): highlight sidebar active root items

### LINKED ISSUE #628: [Bug report] First level sidebar items are not highlighted when active
### Description

When visiting a page that match a root link in the sidebar, it doesn’t get highlighted.

### Steps to reproduce

- Open a page that match with a root link in the sidebar

### Expected behavior

The menu item should be highlighted like those from lower levels are.

### Screenshots

VuePress 1 (correct):

SCR-20220113-jk0

VuePress 2 (wrong):

SCR-20220113-jj7

### Environment info

```bash
  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 349.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/local/bin/git
  Browsers:
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.55
    Firefox: 96.0
    Safari: 15.1
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.33
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  undefined (2.0.0-beta.33)
    @vuepress/client:  2.0.0-beta.33
    @vuepress/core:  2.0.0-beta.33
    @vuepress/markdown:  2.0.0-beta.33
    @vuepress/plugin-active-header-links:  2.0.0-beta.33
    @vuepress/plugin-back-to-top:  2.0.0-beta.33
    @vuepress/plugin-container:  2.0.0-beta.33
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: ^2.0.0-beta.33 => 2.0.0-beta.33
    @vuepress/plugin-external-link-icon:  2.0.0-beta.33
    @vuepress/plugin-git:  2.0.0-beta.33
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.33
    @vuepress/plugin-nprogress:  2.0.0-beta.33
    @vuepress/plugin-palette:  2.0.0-beta.33
    @vuepress/plugin-prismjs:  2.0.0-beta.33
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.33
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.33
    @vuepress/theme-default:  2.0.0-beta.33
    @vuepress/utils:  2.0.0-beta.33
    vue:  3.2.26
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.33 => 2.0.0-beta.33
    vuepress-vite: ^2.0.0-beta.33 => 2.0.0-beta.33
    vuepress-webpack: Not Found
```

### PR DESCRIPTION
**Pull request by LeBenLeBen**
closes #628

### CODE REVIEW

**Comment by meteorlxy** [comment]
It's only highlightable when the root sidebar item is the page link in v1.

As shown below, it won't be highlighted as a group title:

image

**Comment by LeBenLeBen** [comment]
@meteorlxy Oh yes indeed, like this?

**Comment by meteorlxy** [comment]
Well, I think this is not as expected:

image

Consider removing the border-left of `a.sidebar-item:not(.sidebar-heading)` if their is a `a.sidebar-heading`? (or something similar?)

**Comment by meteorlxy** [comment]
Still have some other styles to tweak, so I fixed it in 1a5f4fb. Thank you all the same ❤️

**Pull request closed without merging**
